AWSTemplateFormatVersion: 2010-09-09
Description: IAM managed policy for the api

Parameters:
  Environment:
    Type: String
  Service:
    Type: String
  Api:
    Type: String

Resources:
  ApiFullAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub Full access to API Gateway for ${Service}
      ManagedPolicyName: !Sub ${Service}-fullaccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: execute-api:Invoke
            Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/${Environment}/*/*
